# Generated by Django 2.2.9 on 2020-08-16 10:02

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100)),
                ('faculty', models.TextField()),
                ('link_description', models.TextField()),
                ('link', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('max_marks', models.IntegerField()),
                ('links', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('objective', models.TextField()),
                ('education', models.TextField()),
                ('miscellaneous', models.TextField()),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('test_names', jsonfield.fields.JSONField()),
                ('courses', jsonfield.fields.JSONField()),
                ('skill_set', jsonfield.fields.JSONField()),
                ('coursesnum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('teacher_id', models.IntegerField()),
            ],
        ),
    ]
